### PR TITLE
RDMS Taxonomy

### PR DESCRIPTION
**Pull request by eddie-knight**
This will resolve the need outlined in #48 

Considering the progress made by the group recently, I believe it's time for us to get an early iteration of the outputs. While the output formats are _absolutely_ still subject to change, I hope this can help get the ball rolling to streamline future efforts being made by the group.

1. Migrated suggestions from @smendis-scottlogic, @AdrianHammond and others into `services/database/relational/taxonomy.md`.
2. Separate from (but inspired by) @rowan-baker's work, I took a stab at creating a gherkin feature file with a scenario for each taxonomy feature.
3. Took a stab at what this might look like if we were to compile everything into a single output doc: `services/common-cloud-services.md`. I _did not_ attempt to fully metabolize all of the taxonomy work that's already been done, and this will need to be revised for accuracy if the group enjoys this approach.

### CODE REVIEW

**Comment by AdrianHammond** [comment]
@finos-admin just checking why this has been closed? This PR is being discussed in this #11.

Thanks Adrian

**Comment by mcleo-d** [comment]
Hey @AdrianHammond

Thanks for raising. I'm looking into the closure for you.

@eddie-knight - Are you able to reopen, given that you are the owner of the pull request?

James.

**Comment by eddie-knight** [comment]
Nope, no options visible from my end. Let me know if I should recreate.

**Comment by eddie-knight** [comment]
@mcleo-d @AdrianHammond The issue was caused when the repo went public— it unlinked my fork at that point. I've restored everything, please let me know if you have an option to reopen the PR now.

**Comment by AdrianHammond** [comment]
@eddie-knight  @mcleo-d  - I have reopened this pull request. We can merge once we have agreement via #11

**Comment by AdrianHammond** [comment]
@eddie-knight  - when I try to reopen this PR it re-closes itself. Sorry please could you open and new PR. 

Thanks Adrian

**Comment by eddie-knight** [comment]
Please direct future discussion to issue #82

**Pull request closed without merging**
