### PR TITLE
First draft of comms wg charter

### PR DESCRIPTION
**Pull request by eddie-knight**
Drafted in collaboration with @Alexstpierrework incorporating input from @jared-lambert and @caradelia.

Part of #171

### CODE REVIEW

**Review by AdrianHammond — COMMENTED** [review]
LGTM +1

**Comment by eddie-knight** [comment]
+1

**Comment by jonmuk** [comment]
+1

**Comment by rgriffiths-scottlogic** [comment]
+1 - Approved

**Review by rgriffiths-scottlogic — COMMENTED** [review]
Approved

**Review by pgste — COMMENTED** [review]
+ 1 - Approved

**Review by rgriffiths-scottlogic — APPROVED** [review]

**Pull request merged**
