### PR TITLE
Add lychee as a link checker.

### PR DESCRIPTION
**Pull request by dogle-scottlogic**
Add [lychee](https://github.com/lycheeverse/lychee-action) as a link checker.
Standardise on kebab case for job names

### CODE REVIEW

**Review by sshiells-scottlogic — APPROVED** [review]

**Comment by damienjburks** [comment]
@dogle-scottlogic  add this anywhere under line 7 inside of the `pr_workflow.yml` file:

```yaml
link-checker:
      uses: ./.github/workflows/links.yml
      permissions:
        pull-requests: write
```

**Review by damienjburks — APPROVED** [review]
LGTM!

**Comment by damienjburks** [comment]
@sshiells-scottlogic & @eddie-knight are we good to merge?

**Comment by eddie-knight** [comment]
Sure, we can merge it and adjust later if needed.

Thanks for this @sshiells-scottlogic !

**Comment by eddie-knight** [comment]
Sure, we can merge now and adjust later if needed.

Thanks for this @dogle-scottlogic !

**Pull request merged**
