### PR TITLE
Add in initial threat and control for KeyMgmt service

### PR DESCRIPTION
**Pull request by mlysaght2017**

### CODE REVIEW

**Comment by mlysaght2017** [comment]
@eddie-knight @kazmik23 - initial threat and control - will start adding in more - please review and start adding in as best you can

**Comment by eddie-knight** [comment]
Thanks @mlysaght2017!

I'm taking a stab at GenAI over the weekend and Kamran said he plans to work on KMS threats and controls

**Comment by damienjburks** [comment]
Looks the there are some schema related issues that we need to look into @mlysaght2017

**Comment by sshiells-scottlogic** [comment]
I hope you don't mind @mlysaght2017 but I pushed a small change to adjust the threats schema to update the accpeted pattern. That got rid of the errors in the threats file. There are still some schema issues in the controls file. I suspect that file is work in progress and they will be addressed naturally. If there are any further modifications to the schemas required let me know and I can jump in (might not be straight away as I have various things on this weekend). Alternatively you can make the changes yourselves.

**Comment by mlysaght2017** [comment]
Thanks @sshiells-scottlogic! 

@eddie-knight  - pushed fixes to the controls schema and template. As discussed, we only need mitre ttps in the threats (not the controls). Also, control_mappings should be optional

**Review by eddie-knight — DISMISSED** [review]

**Comment by eddie-knight** [comment]
I think we still need to update Codeowners with the new filenames and such. I have approver rights on that file if someone else can open the PR with the necessary changes.

**Comment by mlysaght2017** [comment]
@damienjburks @smendis-scottlogic can you please approve this starter KMS threat and control

**Review by damienjburks — DISMISSED** [review]

**Review by sshiells-scottlogic — APPROVED** [review]
Lgtm. 

 Shall we schedule a review of the schemas post OSFF to make sure they reflect reality as use cases evolve?

I think at the very least we should have guidelines about updating the schemas if we're submitting changes which don't comply (which at this stage is because we're still figuring things out as we go)?

**Comment by damienjburks** [comment]
@sshiells-scottlogic I agree with you. I created an issue for that: https://github.com/finos/common-cloud-controls/issues/400

**Pull request merged**
