### PR TITLE
Update participants.md - Vicente Herrera Garcia - Control Plane

### PR DESCRIPTION
**Pull request by vicenteherrera**
My name is Vicente Herrera Garcia, and I'd like to formally participate to the Finos Common Cloud Controls project.

By making contribution to this repository, I agree to the terms of the following documents located at: https://github.com/finos/standards-project-blueprint:

(a) Community Specification License 1.0 (.0_Community_Specification_License-v1.md)

(b) Community Specification Governance Policy 1.0 (5._Governance.md)

(c) Community Specification Contribution Policy 1.0 (6._Contributing.md)

(d) Community Specification Code of Conduct (8._Code_of_Conduct.md)

In addition, for source code contributions, I certify that:

(a) The contribution was created in whole or in part by me and I have the right to submit it under the open source license indicated in the file; or (b) The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work with modifications, whether created in whole or in part by me, under the same open source license (unless I am permitted to submit under a different license), as indicated in the file; or (c) The contribution was provided directly to me by some other person who certified (a), (b) or (c) and I have not modified it. (d) I understand and agree that this working group and the contribution may be public and that a record of the contribution (including all personal information I submit with it, including my sign-off) is maintained indefinitely and may be redistributed consistent with this agreement or the open source license(s) involved.

I represent that I am legally entitled to make the grants set forth in the documents above. If my employer(s) has rights to intellectual property that may be infringed by the materials developed by this Working Group, I represent that I have received permission to enter these agreements on behalf of that employer.

### CODE REVIEW

**Comment by vicenteherrera** [comment]
Hi friends, sorry for taking so long to set the PR. Please review and approve, we have sorted out the CLA approving from my company.

**Review by mcleo-d — APPROVED** [review]
LGTM 👍🏻

**Comment by mcleo-d** [comment]
Merging on behalf of @finos/ccc-maintainers

**Comment by mcleo-d** [comment]
Merged on behalf of @finos/ccc-maintainers

Both @vicenteherrera and @mcleo-d have signed the FINOS CCC CLA as demonstrated in EasyCLA.

Screenshot 2023-11-16 at 18 57 43
Screenshot 2023-11-16 at 18 57 27

**Pull request merged**
