### PR TITLE
Correct prompt for common controls, update controls schema, fix broken links.

### PR DESCRIPTION
**Pull request by sshiells-scottlogic**
Correct prompt for common controls
Fix broken links
Update controls schema to allow for service level threats to be specified.

### CODE REVIEW

**Comment by sshiells-scottlogic** [comment]
@eddie-knight can you take a look at this please?

Now that we have all links fixed should we update and prevent merging if someone adds a broken link?

For the yaml-checker @mlysaght2017  do you want to take a look at the inclusion of tactics in services/database/relational/threats.yaml and update accordingly and then we could prevent merge in the case of schema validation failures?

**Review by eddie-knight — APPROVED** [review]
LGTM! Thanks for taking the time to muddle through this

**Comment by eddie-knight** [comment]
@sshiells-scottlogic could you fix the conflicts, and then drop an email to Jared requesting review? I don't think this touches much of the dupred scope, so it should be a quick one for him.

**Comment by sshiells-scottlogic** [comment]
@jared-lambert  can you review this when you get some time please?

**Review by jared-lambert — APPROVED** [review]
Looks good to me

**Pull request merged**
