### PR TITLE
Add in doc on alignment with FINOS AI readiness SIG

### PR DESCRIPTION
**Pull request by mlysaght2017**

### CODE REVIEW

**Comment by mlysaght2017** [comment]
@eddie-knight @jared-lambert wasn't sure where to place this doc, so let me know if we need it somewhere else

**Comment by eddie-knight** [comment]
@sshiells-scottlogic do you have an opinion on this file location?

**Comment by sshiells-scottlogic** [comment]
@eddie-knight  yes, but what that opinion is I am not fully sure. I don't think it belongs to here for sure.

Perhaps it could be in something like: roadmap/reference-architectures ?

**Comment by eddie-knight** [comment]
@sshiells-scottlogic @mlysaght2017 🤔  Would it be better to keep this info in one of the github issues related to the topic?

**Comment by eddie-knight** [comment]
Alternatively, the AI Readiness SIG is working on the "AI Governance Framework" which seems like a prime candidate for the duplication reduction WG's `frameworks` directory

**Comment by sshiells-scottlogic** [comment]
> @sshiells-scottlogic @mlysaght2017 🤔 Would it be better to keep this info in one of the github issues related to the topic?

If we did this there is a chance the issue is closed/deleted and we lose the info?

**Review by eddie-knight — APPROVED** [review]

**Pull request merged**
