### PR TITLE
Convert Object Storage development files from MD to YAML

### PR DESCRIPTION
**Pull request by eddie-knight**
Part of #299.

This PR transforms the Object Storage taxonomy, threats, and controls from markdown into yaml files.

### CODE REVIEW

**Review by mlysaght2017 — APPROVED** [review]
Looks good.

**Review by damienjburks — APPROVED** [review]
LGTM! I'm excited 🚀

**Comment by eddie-knight** [comment]
@smendis-scottlogic Could you take a look at this? The idea is to start moving content into YAML format, then we can use the generator (different PR) to craft Markdown documents at release time.

**Review by mlysaght2017 — COMMENTED** [review]
@eddie-knight - this looks great. I think we just need to add a reference to "threat" as discussed

**Comment by eddie-knight** [comment]
@mlysaght2017 please review to make sure I've made all of the updates we discussed

**Review by sshiells-scottlogic — DISMISSED** [review]
LGTM

**Comment by mlysaght2017** [comment]
We'll need `control_family` and `threats` added too to align to the new template. Happy to approve and get those in later though.

**Comment by eddie-knight** [comment]
Thanks for catching that @mlysaght2017, I'll put up another commit shortly

**Comment by eddie-knight** [comment]
@mlysaght2017 I've added the control families, but wasn't super confident on the threat mappings after I got started on that. Would prefer to leave that for a dedicated follow up PR.

@AdrianHammond or @ojeb2 — could one of y'all approve the changes to CODEOWNERS? This will enable all future similar PRs to be approved by the Security WG.

**Review by damienjburks — APPROVED** [review]

**Review by mlysaght2017 — DISMISSED** [review]

**Comment by eddie-knight** [comment]
Closing this as the required reviewers has gotten wonky.

**Pull request closed without merging**
