### PR TITLE
Adding Auto Formatting Capability - GitHub Actions

### PR DESCRIPTION
**Pull request by damienjburks**
### Summary

This PR addresses the comment made by @eddie-knight in #271. In short, this change allows for automatic formatting of files that have been modified within a PR. This also solves the need for #211, as we truly don't need a hook if we can refer to the Actions as a guide for aligning with linting practices, and auto formatting our Markdown files. 
 
Let me know if you have any questions.

### Impacted Changes
- #271 
- #211

### CODE REVIEW

**Comment by damienjburks** [comment]
@eddie-knight  i might need your help adding this bot to the project to allow it to check in changes via a PR: 

github-actions[bot]
41898282+github-actions[bot]@users.noreply.github.com

**Comment by eddie-knight** [comment]
Hmmm... Is there some middle ground, to where a github action can give remediation information without automatically modiying the PR or repo?

**Comment by damienjburks** [comment]
@eddie-knight we could have the bot make a comment on the PR to recommend running Prettier to format the selected Markdown files? That might be a better alternative.

**Comment by eddie-knight** [comment]
To bring in another angle...

I've drafted a script that we can use to generate the release markdown from YAML development files. 

If we want to move in that direction, we won't have to worry about style differences in release assets.

**Pull request closed without merging**
