### PR TITLE
Add common features and threats snippets

### PR DESCRIPTION
**Pull request by sshiells-scottlogic**
Add common features and threat snippets to help ease and speed up development.

Common control snippets and instructions on how to use are to follow in a separate PR.

As a quick start if you type "CF" or "CT" in vscode suggestions for complete show up.

image

image

### CODE REVIEW

**Comment by eddie-knight** [comment]
@mlysaght2017 FYI

**Comment by eddie-knight** [comment]
cc @kazmik23 in case this helps with your work also

**Comment by sshiells-scottlogic** [comment]
> @sshiells-scottlogic - This is a brilliant idea. thank you so much for this.
> 
> Would you be able to add some documentation around this inside of content-standards-and-practices folder please?

@damienjburks, @dogle-scottlogic is going to add docs next week along with snippets for the common controls. I am heading out on vacation in a few hours so don't have time to that as part of this PR.

**Comment by damienjburks** [comment]
sweet - could you create a issue, assign it to @dogle-scottlogic, and drop the link in this ticket in this PR? After that, I'll approve.

**Comment by sshiells-scottlogic** [comment]
[Link to issue](https://github.com/finos/common-cloud-controls/issues/438)

For some reason @dogle-scottlogic I can't seem to assign you to tasks or PRs but can tag you in comments. Can you assign yourself to this issue?

**Comment by dogle-scottlogic** [comment]
> [Link to issue](https://github.com/finos/common-cloud-controls/issues/438)
> 
> For some reason @dogle-scottlogic I can't seem to assign you to tasks or PRs but can tag you in comments. Can you assign yourself to this issue?

@sshiells-scottlogic can't assign myself either 😕

**Review by damienjburks — APPROVED** [review]
it's all good - i'll have to work with @eddie-knight to figure that out! Approved!

**Pull request merged**
