### PR TITLE
Adding a policy and recommendations recommendation

### PR DESCRIPTION
**Pull request by sshiells-scottlogic**
Add a recommendation on how policy/recommendations are proposed and managed.

### CODE REVIEW

**Review by smendis-scottlogic — APPROVED** [review]
Looks good to me

**Comment by sshiells-scottlogic** [comment]
@eddie-knight a quick recommendation about policies and recommendations

**Comment by eddie-knight** [comment]
QQ: Is there anything that should be harmonized between this proposal and this?

https://github.com/finos/common-cloud-controls/blob/main/docs/governance/community-guidelines/README.md

**Comment by sshiells-scottlogic** [comment]
We can delete this PR. I missed this. On my local copy it showed that this recommendation hadn't been pushed and I thought I forgot to push it while I was travelling. I only looked at the recommendation files and not the README so thought it was still missing but I just didn't look cloesly enough.

**Comment by eddie-knight** [comment]
Anything else you want to capture in the existing docs after giving it more thought?

**Comment by sshiells-scottlogic** [comment]
Nothing with regards to this.

**Pull request closed without merging**
