### PR TITLE
Minor fixes to the CODEOWNERS file

### PR DESCRIPTION
**Pull request by eddie-knight**
I'm still not sure that our teams have the correct permissions, but I'm hoping this makes the directory ownership work.

### CODE REVIEW

**Comment by eddie-knight** [comment]
The check failures don't apply to changes in this PR

**Comment by eddie-knight** [comment]
@sshiells-scottlogic @damienjburks Can either of yall take a look at this?

I like that merging is a lot faster with CODEOWNERS broken 😆 but I'd prefer we refine the codeowners usage instead of just leaving it broken. Hoping this gets it turned back on, then we can refine it more later.

**Review by damienjburks — COMMENTED** [review]
@eddie-knight this is the exception that I'm getting:

```
Unknown owner on line 17: make sure the team @finos/ccc-wg-delivery exists, is publicly visible, and has write access to the repository
```

it seems to be repeated for every working group... I'm assuming the permissions for each team is already created properly right?

**Comment by eddie-knight** [comment]
@damienjburks I suspect there is an issue with the teams settings, and this PR may be a red herring, but I'd like to rule this out as a contributing factor before we set up time with FINOS to investigate all of the teams.

**Comment by sshiells-scottlogic** [comment]
@eddie-knight  are you just looking for an approval here? Or to look into the actual issue?

**Comment by eddie-knight** [comment]
@sshiells-scottlogic Looking to merge this and confirm whether it impacts the issue. Then I'll swing back around with help@finos to figure out the teams settings.

**Review by damienjburks — APPROVED** [review]

**Comment by damienjburks** [comment]
@eddie-knight okay - merging this in now then.

**Pull request merged**
