### PR TITLE
Added training doc for OSCAL to CCC docs

### PR DESCRIPTION
**Pull request by ianmiell**

### CODE REVIEW

**Review by iMichaela — APPROVED** [review]
LGTM

**Comment by iMichaela** [comment]
@ianmiell - I believe you need to open a ticket for request support with the EasyCLA error above. Thank you fro creating the  oscal.md document.

**Comment by mcleo-d** [comment]
Merged on behalf of @iMichaela and `OSCAL Representation of FINOS CCC` - cc @jonmuk  and @finos/ccc-maintainers

**Comment by mcleo-d** [comment]
Thank you @ianmiell for your awesome contribution!

**Comment by rachkim00** [comment]
Thank you @ianmiell !

**Pull request merged**
