### PR TITLE
Vscode schema

### PR DESCRIPTION
**Pull request by eddie-knight**
follows #377 

Everything still works as expected:

Screenshot 2024-09-21 at 15 18 17

### CODE REVIEW

**Comment by eddie-knight** [comment]
@dogle-scottlogic WDYT of this?

**Comment by dogle-scottlogic** [comment]
Looks good 👍

**Review by damienjburks — APPROVED** [review]

**Comment by eddie-knight** [comment]
Ah— @damienjburks we need to update CODEOWNERS so that `.vscode` is owned by @finos/ccc-wg-delivery. Could you make a PR for that?

And we need @sshiells-scottlogic to approve the guidelines dir changes on behalf of @finos/ccc-wg-community-structure

**Review by damienjburks — DISMISSED** [review]

**Comment by eddie-knight** [comment]
Alrighty— this is only pending approval from @sshiells-scottlogic / @finos/ccc-wg-community-structure now

**Review by damienjburks — APPROVED** [review]

**Pull request closed without merging**
