### PR TITLE
Machine Learning Development Environment Threats & Controls

### PR DESCRIPTION
**Pull request by eddie-knight**
Drafted in collaboration with @kazmik23

### CODE REVIEW

**Comment by smendis-scottlogic** [comment]
Hi @eddie-knight do you want me to come up with features.yaml for this?

**Comment by kazmik23** [comment]
hey @smendis-scottlogic @eddie-knight already currently working on features for MLDE :)

**Comment by eddie-knight** [comment]
Thanks both! If either of you can contribute that, I'd greatly appreciate it :D

**Comment by eddie-knight** [comment]
Moved to #451 and #452

**Pull request closed without merging**
