### PR TITLE
#207 - DoD First Iteration

### PR DESCRIPTION
**Pull request by smendis-scottlogic**

### CODE REVIEW

**Comment by sshiells-scottlogic** [comment]
@eddie-knight  I think the plan was to have this moved to being a policy and a PR to be opened ahead of the next all hands so we can go through and discuss it there since it is something everyone should contribute to / sign off?

**Comment by eddie-knight** [comment]
You're right that we already discussed this, thanks @smendis-scottlogic 

Let's follow the [Upgrading a Guideline to a Policy](https://github.com/finos/common-cloud-controls/blob/main/docs/governance/community-guidelines/README.md/#upgrading-a-recommendation-to-become-a-policy) process that Stevie created. 

We'll start by contributing this in a Guideline format, then based on community feedback I'll sponsor ia vote on the next SC meeting.

**Comment by sshiells-scottlogic** [comment]
@smendis-scottlogic  are you good to make the adjustments?

**Comment by smendis-scottlogic** [comment]
Closing this MR and reopening following the forking for PR guideline suggested by the Community Structure WG

**Pull request closed without merging**
