### PR TITLE
Update participants.md

### PR DESCRIPTION
**Pull request by kazmik23**

### CODE REVIEW

**Comment by eddie-knight** [comment]
@TheJuanAndOnly99 can you try kicking EasyCLA?

**Comment by TheJuanAndOnly99** [comment]
Hi @kazmik23 please follow the instructions left by the [EasyCLA bot above](https://github.com/finos/common-cloud-controls/pull/395#issuecomment-2363938440), click on "please click here to be authorized" and follow the instructions. If you need any additional help you can submit a support ticket as well!

**Review by eddie-knight — APPROVED** [review]

**Pull request merged**
