### PR TITLE
PR provides OSCAL catalog examples and validation approach with oscal-cli .

### PR DESCRIPTION
**Pull request by iMichaela**
The PR is providing examples directory and catalog examples are as follows:

- [examples](./examples): This directory contains sample OSCAL content organized by OSCAL models. 
- [examples/catalog](./examples/catalog): This directory contains sample OSCAL content organized by OSCAL models.
- [examples/catalog/xml](./examples/catalog/xml): XML representations of the OSCAL CCC catalog examples.
- [examples/catalog/json](./examples/catalog/json): JSON representations of the OSCAL CCC catalog examples.
- [examples/catalog/yaml](./examples/catalog/yaml): YAML representations of the OSCAL CCC catalog examples.

Additionally, a Makefile that installs locally the `oscal-cli` tool for content reformatting and validation.

### CODE REVIEW

**Comment by iMichaela** [comment]
@finos-admin - Since NIST is not a participating organization, I signed an individual CLA, but the system is still complaining.  Assistance is needed.

**Comment by rachkim00** [comment]
@iMichaela I am having trouble accessing example catalog files. Getting 404 errors. Could you check the links?

**Comment by iMichaela** [comment]
@rachkim00 - you go the pull requests tab, select the PR, and then go to files, and all of them will be there in full since they are  new. My fork is private because CCC repo is private.  I can invite you to my repo too as collaborator.

**Comment by eddie-knight** [comment]
Really happy to see progress on making legitimate OSCAL contributions following the vision cast in the whitepaper— thanks for doing this @iMichaela 

My only concern is in contributing "examples" as I interpret this to mean that the contribution is non-functional.

Would it make sense to continue working on this (prior to merging) to convert these into functional contributions? The benefit of that would be that this gives folks a tangible goal to pursue and rally around, with the final output being something we can show as genuine progress.

**Comment by iMichaela** [comment]
> Really happy to see progress on making legitimate OSCAL contributions following the vision cast in the whitepaper— thanks for doing this @iMichaela
> 
> My only concern is in contributing "examples" as I interpret this to mean that the contribution is non-functional.
> 
> Would it make sense to continue working on this (prior to merging) to convert these into functional contributions? The benefit of that would be that this gives folks a tangible goal to pursue and rally around, with the final output being something we can show as genuine progress.

@eddie-knight No contribution can be function until the conversion to OSCAL approach  is align with the assessment and reporting process to support it.  I raised it over and over. Once that is decided (reviews using examples), tools will be necessary to convert the information from its original source (hopefully not word documents). I raised this issue too, because no tool will be efficient in converting (and maintaining the information in OSCAL as future changes will take place, IF there is no proper consistency in the structure the information is provided.

As OSCAL Director , I am here to help guide the process, but I do not make decisions.

**Review by rachkim00 — APPROVED** [review]
This is wonderful catalog samples and you even provided different options! Looks great. Thank you @iMichaela.

**Comment by iMichaela** [comment]
Thank you, @rachkim00 . The PR also includes a Makefile to validate the examples and future catalogs with our OSCAL-cli tool which the Makefile will download for you.

**Comment by ianmiell** [comment]
Looks useful, especially the Makefile validation of examples! Thanks.

**Pull request merged**
