### PR TITLE
Adding In Logo Wall and Updating Release Notes Template

### PR DESCRIPTION
**Pull request by damienjburks**

### CODE REVIEW

**Comment by eddie-knight** [comment]
Happy to approve this in it's current state, but I'm curious... what's the long-term plan for multiple releases? Will we always use the same logo-wall?

**Comment by damienjburks** [comment]
@eddie-knight the goal i had in mind was to keep the same logo wall and update it we have more organizations represented with future releases. Sent an email out to get more opinions on this idea/approach.

**Review by eddie-knight — APPROVED** [review]
LGTM— can refine more based on feedback

**Comment by rgriffiths-scottlogic** [comment]
Apologies for the delay - I've been on holiday!
I like the look of the wall right now - it's nice & clean :-)
I'm 100% good to approve this right now "as is" with the following thoughts:
If we're lucky enough to attract dozens more contributors from different entities, would it still look as nice/clean? Would there be any distinction between the contributors based on their actual efforts? I'm not suggesting a size-related logo! Is it worth thinking about how to recognise the early / major / significant contributors? (Another question is who decides what is "significant"?). Food for thought for when we have that nice problem to deal with!

**Pull request merged**
