### PR TITLE
CCC Whitepaper Word Document

### PR DESCRIPTION
**Pull request by crawfordchanel**
Common Cloud Control Standard in word document format
[Logical Controls to extended OSCAL.docx](https://github.com/finos/common-cloud-controls/files/14224252/Logical.Controls.to.extended.OSCAL.docx)

```git commit```

### CODE REVIEW

**Comment by crawfordchanel** [comment]
@eddie-knight Hi Eddie :) 

Is this draft done correctly? Michaela sent a few OSCAL representation samples over I'd like to create PR's for as well.

**Comment by eddie-knight** [comment]
If you look at the files changed, it seems that the changes aren't what you were intending.
Screenshot 2024-02-09 at 10 58 01 AM

Let me try making a PR and I'll tag you in a few minutes to see if that's what you were going for.

**Comment by eddie-knight** [comment]
@crawfordchanel please check PR #123 to see if it accomplishes your intent here

**Comment by crawfordchanel** [comment]
> @crawfordchanel please check PR #123 to see if it accomplishes your intent here
> 
> I can hop on a call today if you'd like help making PRs like that with the other content you mentioned

Yes. Let's get on a zoom call. 2pm EST? I'm flexible (Meeting ID 947 662 2996 PC 011554) Michaela was able to use the document I sent to draft YAML and JSON samples.

**Comment by crawfordchanel** [comment]
That works! See you then.

**Pull request closed without merging**
